# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syntax_definition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17syntax_definition.proto\x12\x08learning\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cReplyMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\tHandShake\x12\x44\n\x0e\x44oingHandShake\x12\x18.learning.RequestMessage\x1a\x16.learning.ReplyMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syntax_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=37
  _globals['_REQUESTMESSAGE']._serialized_end=70
  _globals['_REPLYMESSAGE']._serialized_start=72
  _globals['_REPLYMESSAGE']._serialized_end=103
  _globals['_HANDSHAKE']._serialized_start=105
  _globals['_HANDSHAKE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
